"""Pydantic schemas for persisted events and structured runtime communication.

Deterministic metadata such as ids, timestamps, sequence numbers, correlation
ids, and retrieval bounds is generated by application code rather than LLMs.
Model-output schemas should prefer enums, booleans, ids, and indices; a model-
authored index is bounded by the concrete application-owned collection supplied
for that call rather than by an unrelated global magic number.
"""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, Field, model_validator


class EventType(str, Enum):
    USER_PROMPT = "USER_PROMPT"
    AGENT_DECISION = "AGENT_DECISION"  # historical v0.1-v0.6 ontology
    RETRIEVAL_REQUEST = "RETRIEVAL_REQUEST"  # legacy v0.1-v0.5 path
    RETRIEVAL_RESULT = "RETRIEVAL_RESULT"  # legacy v0.1-v0.5 path
    MEMORY_REQUEST = "MEMORY_REQUEST"
    MEMORY_PACKET = "MEMORY_PACKET"
    AGENT_DELEGATION = "AGENT_DELEGATION"  # historical v0.1-v0.6 ontology
    AGENT_RESULT = "AGENT_RESULT"  # historical v0.1-v0.6 ontology
    TOOL_REQUEST = "TOOL_REQUEST"
    TOOL_RESULT = "TOOL_RESULT"
    AGENT_RESPONSE = "AGENT_RESPONSE"  # historical v0.1-v0.6 ontology
    CAPABILITY_REQUEST = "CAPABILITY_REQUEST"
    CAPABILITY_PACKET = "CAPABILITY_PACKET"
    CAPABILITY_RESULT = "CAPABILITY_RESULT"
    INTERACTION_RESPONSE = "INTERACTION_RESPONSE"
    INTERACTION_WORKING_STATE = "INTERACTION_WORKING_STATE"
    PERCEPT_OBSERVATION = "PERCEPT_OBSERVATION"
    DERIVED_REPRESENTATION = "DERIVED_REPRESENTATION"
    SYSTEM_EVENT = "SYSTEM_EVENT"
    ERROR = "ERROR"


class Event(BaseModel):
    """A single row of the append-only event log, as read back from storage."""

    event_id: UUID
    conversation_id: UUID
    correlation_id: UUID
    global_seq: int
    conversation_seq: int
    event_type: EventType
    source: str
    created_at: datetime
    payload: dict[str, Any]
    schema_version: int = 1


class KnowledgeOrigin(str, Enum):
    """Separates persisted internal memory from outside information acquisition."""

    INTERNAL_MEMORY = "INTERNAL_MEMORY"
    EXTERNAL_TOOL = "EXTERNAL_TOOL"


class MemoryNeed(BaseModel):
    """Stable system-facing description of an internal information need.

    This contract intentionally contains no candidate-router, association,
    full-text, embedding, or other retrieval-implementation controls. Active
    event IDs are provenance pointers supplied by durable working state and are
    rehydrated as direct context. Focus event IDs are canonical candidate events
    selected by index from a prior MemoryPacket; runtime code validates those
    indices against that exact packet before resolving them to event IDs.
    """

    query_text: str | None = None
    supplemental_query_texts: list[str] = Field(
        default_factory=list,
        description=(
            "Alternate formulations of the same information need. They may be "
            "tried only when the canonical query yields no evidence."
        ),
    )
    entities: list[str] = Field(default_factory=list)
    active_event_ids: list[UUID] = Field(
        default_factory=list,
        max_length=12,
        description=(
            "Canonical event IDs already activated by durable working state. "
            "These are provenance cues, not copied memory content."
        ),
    )
    focus_event_ids: list[UUID] = Field(
        default_factory=list,
        description=(
            "Canonical candidate events selected from a prior MemoryPacket. "
            "They seed deeper deterministic association traversal."
        ),
    )
    include_persisted_history: bool = True
    reference_time: datetime | None = None
    conversation_id: UUID | None = Field(
        default=None,
        description="Optional conversation cue; not a hard memory wall.",
    )
    source_types: list[EventType] | None = None
    limit: int = Field(default=5, ge=1)

    @model_validator(mode="after")
    def validate_event_cues(self) -> "MemoryNeed":
        if len(self.active_event_ids) != len(set(self.active_event_ids)):
            raise ValueError("active_event_ids must not contain duplicates")
        if len(self.focus_event_ids) != len(set(self.focus_event_ids)):
            raise ValueError("focus_event_ids must not contain duplicates")
        return self


class MemoryEvidence(BaseModel):
    """One canonical source event surfaced through the shared JIT Memory API."""

    source_event_id: UUID
    event_type: EventType
    source: str
    created_at: datetime
    conversation_id: UUID
    conversation_seq: int
    global_seq: int
    content: str
    score: float | None = None
    retrieval_reasons: list[str] = Field(default_factory=list)
    provenance_event_ids: list[UUID] = Field(default_factory=list)


class MemoryPacket(BaseModel):
    """Bounded internal evidence packet returned to stateless cognition."""

    memory_request_id: UUID
    origin: Literal[KnowledgeOrigin.INTERNAL_MEMORY] = KnowledgeOrigin.INTERNAL_MEMORY
    need: MemoryNeed
    supported: bool
    items: list[MemoryEvidence]
    retrieval_trace: dict[str, Any] = Field(default_factory=dict)


class RetrievalRequest(BaseModel):
    """Legacy MVP retrieval request retained for regression compatibility."""

    query_text: str | None = Field(
        default=None,
        description="Free-text description of the context needed, used for keyword search.",
    )
    conversation_scope: Literal["CURRENT_CONVERSATION", "ALL_CONVERSATIONS"] = "CURRENT_CONVERSATION"
    source_types: list[EventType] | None = Field(
        default=None, description="Restrict to these event types, if given."
    )
    ordering: Literal["CHRON_ASC", "CHRON_DESC", "RELEVANCE"] = "CHRON_DESC"
    limit: int = Field(default=5, ge=1)


class RetrievalItem(BaseModel):
    """One item returned by the legacy Retrieval Service."""

    source_event_id: UUID
    event_type: EventType
    created_at: datetime
    conversation_id: UUID
    conversation_seq: int
    global_seq: int
    content: str
    rank: float | None = None


class RetrievalResult(BaseModel):
    items: list[RetrievalItem]
