package org.prometheist.node;

import android.content.Context;
import android.security.keystore.KeyGenParameterSpec;
import android.security.keystore.KeyProperties;
import java.nio.charset.StandardCharsets;
import java.security.KeyStore;
import java.util.Arrays;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;

/** Android Keystore AES-GCM; IV generated by provider, immutable record ID as AAD. */
public final class Vault {
  private final SecretKey key;

  public Vault(Context context, boolean hasEvidence) throws Exception {
    KeyStore keys = KeyStore.getInstance("AndroidKeyStore");
    keys.load(null);
    String alias = "prometheist.node.v1";
    if (!keys.containsAlias(alias)) {
      if (hasEvidence)
        throw new IllegalStateException(
            "Encryption key missing. Restore/export recovery required.");
      KeyGenerator gen =
          KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore");
      gen.init(
          new KeyGenParameterSpec.Builder(
                  alias, KeyProperties.PURPOSE_ENCRYPT | KeyProperties.PURPOSE_DECRYPT)
              .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
              .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
              .setKeySize(256)
              .build());
      gen.generateKey();
    }
    key = (SecretKey) keys.getKey(alias, null);
  }

  public byte[] seal(byte[] raw, String id) throws Exception {
    Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
    cipher.init(Cipher.ENCRYPT_MODE, key);
    cipher.updateAAD(id.getBytes(StandardCharsets.UTF_8));
    byte[] ciphertext = cipher.doFinal(raw), iv = cipher.getIV();
    byte[] result = Arrays.copyOf(iv, iv.length + ciphertext.length);
    System.arraycopy(ciphertext, 0, result, iv.length, ciphertext.length);
    return result;
  }

  public byte[] open(byte[] envelope, String id) throws Exception {
    Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
    cipher.init(Cipher.DECRYPT_MODE, key, new GCMParameterSpec(128, envelope, 0, 12));
    cipher.updateAAD(id.getBytes(StandardCharsets.UTF_8));
    return cipher.doFinal(envelope, 12, envelope.length - 12);
  }
}
