"""Pydantic schemas for persisted events and structured agent communication.

Deterministic metadata such as ids, timestamps, sequence numbers, correlation
ids, and retrieval bounds is generated by application code rather than LLMs.
"""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, Field, model_validator


class EventType(str, Enum):
    USER_PROMPT = "USER_PROMPT"
    AGENT_DECISION = "AGENT_DECISION"
    RETRIEVAL_REQUEST = "RETRIEVAL_REQUEST"  # legacy v0.1-v0.5 path
    RETRIEVAL_RESULT = "RETRIEVAL_RESULT"  # legacy v0.1-v0.5 path
    MEMORY_REQUEST = "MEMORY_REQUEST"
    MEMORY_PACKET = "MEMORY_PACKET"
    CAPABILITY_REQUEST = "CAPABILITY_REQUEST"
    CAPABILITY_PACKET = "CAPABILITY_PACKET"
    AGENT_DELEGATION = "AGENT_DELEGATION"
    AGENT_RESULT = "AGENT_RESULT"
    TOOL_REQUEST = "TOOL_REQUEST"
    TOOL_RESULT = "TOOL_RESULT"
    AGENT_RESPONSE = "AGENT_RESPONSE"
    SYSTEM_EVENT = "SYSTEM_EVENT"
    ERROR = "ERROR"


class Event(BaseModel):
    """A single row of the append-only event log, as read back from storage."""

    event_id: UUID
    conversation_id: UUID
    correlation_id: UUID
    global_seq: int
    conversation_seq: int
    event_type: EventType
    source: str
    created_at: datetime
    payload: dict[str, Any]
    schema_version: int = 1


class AgentAction(str, Enum):
    """Minimal control choices available to every stateless LLM agent."""

    RESPOND_DIRECTLY = "RESPOND_DIRECTLY"
    REQUEST_CAPABILITY = "REQUEST_CAPABILITY"


class SemanticRetrievalTarget(str, Enum):
    """Bounded query-time semantics used only to shape embedding retrieval.

    These values are soft retrieval intent. They never label persisted events,
    create graph edges, or become authoritative memory facts.
    """

    FACT = "FACT"
    CURRENT_STATE = "CURRENT_STATE"
    PRIOR_STATE = "PRIOR_STATE"
    STATE_TRANSITION = "STATE_TRANSITION"
    IDENTITY = "IDENTITY"
    RELATIONSHIP = "RELATIONSHIP"
    LOCATION = "LOCATION"
    TIME = "TIME"
    VALUE = "VALUE"
    BOOLEAN_STATUS = "BOOLEAN_STATUS"
    PREFERENCE = "PREFERENCE"
    PROCEDURE = "PROCEDURE"
    GENERAL = "GENERAL"


class SemanticTemporalFocus(str, Enum):
    CURRENT = "CURRENT"
    PREVIOUS = "PREVIOUS"
    AS_OF_REFERENCE_TIME = "AS_OF_REFERENCE_TIME"
    HISTORICAL = "HISTORICAL"
    UNSPECIFIED = "UNSPECIFIED"


class SemanticRetrievalIntentV1(BaseModel):
    """Versioned, deliberately narrow semantic-retrieval hint.

    The requesting LLM may select only these bounded categories. Deterministic
    code renders the actual Qwen embedding instruction from them, preventing
    free-form model prose from inventing sources, locations, relationships, or
    other supposed facts during retrieval planning.
    """

    schema_version: Literal[1] = 1
    target: SemanticRetrievalTarget = SemanticRetrievalTarget.GENERAL
    temporal_focus: SemanticTemporalFocus = SemanticTemporalFocus.UNSPECIFIED


class AgentDecision(BaseModel):
    """Minimal structured output of a stateless agent decision step.

    ``capability_query`` is for discovery: it describes what kind of system
    functionality is required. ``capability_input`` is optional invocation data:
    it carries a narrower self-contained subtask or information need to whichever
    capability the registry selects. Keeping them separate prevents discovery
    language from contaminating capability-specific inputs such as memory queries.

    ``retrieval_intent`` is optional query-time metadata for requests that need
    persisted internal memory. It is never used to classify stored events.
    """

    action: AgentAction
    capability_query: str | None = Field(
        default=None,
        description=(
            "When requesting a capability, briefly describe the additional "
            "functionality or information access needed without naming an implementation."
        ),
    )
    capability_input: str | None = Field(
        default=None,
        description=(
            "Optional narrower self-contained input for the selected capability. "
            "Omit when the whole current task should be passed unchanged."
        ),
    )
    retrieval_intent: SemanticRetrievalIntentV1 | None = Field(
        default=None,
        description=(
            "Optional bounded retrieval intent when persisted internal history is needed. "
            "Do not populate it for unrelated capabilities."
        ),
    )

    @model_validator(mode="after")
    def require_capability_query(self) -> "AgentDecision":
        if self.action == AgentAction.REQUEST_CAPABILITY:
            if self.capability_query is None or not self.capability_query.strip():
                raise ValueError("REQUEST_CAPABILITY requires capability_query")
        return self


class KnowledgeOrigin(str, Enum):
    """Separates persisted internal memory from outside information acquisition."""

    INTERNAL_MEMORY = "INTERNAL_MEMORY"
    EXTERNAL_TOOL = "EXTERNAL_TOOL"


class CapabilityKind(str, Enum):
    """Current executable capability classes exposed by the system registry."""

    AGENT = "AGENT"
    SERVICE = "SERVICE"
    TOOL = "TOOL"


class CapabilityNeed(BaseModel):
    """A caller-owned description of functionality needed from the current system.

    The exact task is the canonical discovery cue. Optional LLM-generated hints
    may be tried only if canonical discovery returns nothing. Implementations,
    executors, and routing policy remain application-owned.
    """

    query_text: str
    supplemental_query_texts: list[str] = Field(default_factory=list, max_length=3)
    kinds: list[CapabilityKind] | None = None
    exclude_capability_ids: list[str] = Field(default_factory=list)
    limit: int = Field(default=3, ge=1, le=10)


class CapabilityDescriptor(BaseModel):
    """Small public description safe to reveal only when a capability is relevant."""

    capability_id: str
    kind: CapabilityKind
    description: str


class CapabilityMatch(BaseModel):
    descriptor: CapabilityDescriptor
    score: float
    matched_terms: list[str] = Field(default_factory=list)


class CapabilityPacket(BaseModel):
    """Bounded deterministic capability-discovery result."""

    capability_request_id: UUID
    need: CapabilityNeed
    matches: list[CapabilityMatch]
    selected_query_role: Literal["canonical", "supplemental"] | None = None
    selected_query_text: str | None = None


class MemoryNeed(BaseModel):
    """Typed input contract of the registered ``internal_memory`` capability.

    This contract intentionally contains no candidate-router, association,
    full-text, embedding-model, vector-dimension, or other implementation knobs.
    ``semantic_intent`` is query meaning, not retrieval policy.
    """

    query_text: str | None = None
    supplemental_query_texts: list[str] = Field(
        default_factory=list,
        max_length=3,
        description=(
            "Bounded alternate formulations of the same information need. "
            "They may be tried only when the canonical query yields no evidence."
        ),
    )
    semantic_intent: SemanticRetrievalIntentV1 | None = None
    entities: list[str] = Field(default_factory=list)
    reference_time: datetime | None = None
    conversation_id: UUID | None = Field(
        default=None,
        description="Optional conversation cue; not a hard memory wall.",
    )
    source_types: list[EventType] | None = None
    limit: int = Field(default=5, ge=1, le=20)


class MemoryNeedDecision(BaseModel):
    """Legacy semantic memory-plan schema retained for compatibility tests."""

    query_text: str
    entities: list[str] = Field(default_factory=list)


class EvidenceStatus(str, Enum):
    """Epistemic status of an item returned through JIT Memory."""

    ADMITTED = "ADMITTED"
    SEMANTIC_CANDIDATE = "SEMANTIC_CANDIDATE"


class MemoryEvidence(BaseModel):
    """One canonical source event surfaced by the internal-memory capability."""

    source_event_id: UUID
    event_type: EventType
    source: str
    created_at: datetime
    conversation_id: UUID
    conversation_seq: int
    global_seq: int
    content: str
    score: float | None = None
    evidence_status: EvidenceStatus = EvidenceStatus.ADMITTED
    retrieval_reasons: list[str] = Field(default_factory=list)
    provenance_event_ids: list[UUID] = Field(default_factory=list)


class MemoryPacket(BaseModel):
    """Bounded evidence/candidate packet returned by ``internal_memory``.

    ``supported`` is true only when deterministic evidence admission succeeded.
    A packet may contain ``SEMANTIC_CANDIDATE`` items while supported is false;
    those items are retrieval leads, not asserted facts or graph relationships.
    """

    memory_request_id: UUID
    origin: Literal[KnowledgeOrigin.INTERNAL_MEMORY] = KnowledgeOrigin.INTERNAL_MEMORY
    need: MemoryNeed
    supported: bool
    items: list[MemoryEvidence]
    retrieval_trace: dict[str, Any] = Field(default_factory=dict)


class AgentDelegation(BaseModel):
    specialist: str
    task: str
    capability_request_id: UUID | None = None


class AgentResult(BaseModel):
    specialist: str
    task: str
    text: str
    memory_request_ids: list[UUID] = Field(default_factory=list)
    evidence_event_ids: list[UUID] = Field(default_factory=list)


class RetrievalRequest(BaseModel):
    """Legacy MVP retrieval request retained for regression compatibility."""

    query_text: str | None = Field(
        default=None,
        description="Free-text description of the context needed, used for keyword search.",
    )
    conversation_scope: Literal["CURRENT_CONVERSATION", "ALL_CONVERSATIONS"] = "CURRENT_CONVERSATION"
    source_types: list[EventType] | None = Field(
        default=None, description="Restrict to these event types, if given."
    )
    ordering: Literal["CHRON_ASC", "CHRON_DESC", "RELEVANCE"] = "CHRON_DESC"
    limit: int = Field(default=5, ge=1, le=20)


class RetrievalItem(BaseModel):
    """One item returned by the legacy Retrieval Service."""

    source_event_id: UUID
    event_type: EventType
    created_at: datetime
    conversation_id: UUID
    conversation_seq: int
    global_seq: int
    content: str
    rank: float | None = None


class RetrievalResult(BaseModel):
    items: list[RetrievalItem]
