"""Pydantic schemas for persisted events and structured runtime communication.

Deterministic metadata such as ids, timestamps, sequence numbers, correlation
ids, and retrieval bounds is generated by application code rather than LLMs.
Model-output schemas should prefer enums, booleans, ids, and bounded indices;
free-form text is reserved for user-facing language or irreducibly semantic
content.
"""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, Field, model_validator


class EventType(str, Enum):
    USER_PROMPT = "USER_PROMPT"
    AGENT_DECISION = "AGENT_DECISION"  # historical v0.1-v0.6 ontology
    RETRIEVAL_REQUEST = "RETRIEVAL_REQUEST"  # legacy v0.1-v0.5 path
    RETRIEVAL_RESULT = "RETRIEVAL_RESULT"  # legacy v0.1-v0.5 path
    MEMORY_REQUEST = "MEMORY_REQUEST"
    MEMORY_PACKET = "MEMORY_PACKET"
    AGENT_DELEGATION = "AGENT_DELEGATION"  # historical v0.1-v0.6 ontology
    AGENT_RESULT = "AGENT_RESULT"  # historical v0.1-v0.6 ontology
    TOOL_REQUEST = "TOOL_REQUEST"
    TOOL_RESULT = "TOOL_RESULT"
    AGENT_RESPONSE = "AGENT_RESPONSE"  # historical v0.1-v0.6 ontology
    CAPABILITY_REQUEST = "CAPABILITY_REQUEST"
    CAPABILITY_PACKET = "CAPABILITY_PACKET"
    CAPABILITY_RESULT = "CAPABILITY_RESULT"
    INTERACTION_RESPONSE = "INTERACTION_RESPONSE"
    INTERACTION_WORKING_STATE = "INTERACTION_WORKING_STATE"
    SYSTEM_EVENT = "SYSTEM_EVENT"
    ERROR = "ERROR"


class Event(BaseModel):
    """A single row of the append-only event log, as read back from storage."""

    event_id: UUID
    conversation_id: UUID
    correlation_id: UUID
    global_seq: int
    conversation_seq: int
    event_type: EventType
    source: str
    created_at: datetime
    payload: dict[str, Any]
    schema_version: int = 1


class KnowledgeOrigin(str, Enum):
    """Separates persisted internal memory from outside information acquisition."""

    INTERNAL_MEMORY = "INTERNAL_MEMORY"
    EXTERNAL_TOOL = "EXTERNAL_TOOL"


class MemoryNeed(BaseModel):
    """Stable MAS-facing description of an internal information need.

    This contract intentionally contains no candidate-router, association,
    full-text, embedding, or other retrieval-implementation controls. Active
    event IDs are provenance pointers supplied by durable working state; they
    identify canonical evidence already active in the current situation rather
    than bypassing or replacing the event ledger.
    """

    query_text: str | None = None
    supplemental_query_texts: list[str] = Field(
        default_factory=list,
        max_length=3,
        description=(
            "Bounded alternate formulations of the same information need. "
            "They may be tried only when the canonical query yields no evidence."
        ),
    )
    entities: list[str] = Field(default_factory=list)
    active_event_ids: list[UUID] = Field(
        default_factory=list,
        max_length=12,
        description=(
            "Canonical event IDs already activated by durable working state. "
            "These are provenance cues, not copied memory content."
        ),
    )
    include_persisted_history: bool = True
    reference_time: datetime | None = None
    conversation_id: UUID | None = Field(
        default=None,
        description="Optional conversation cue; not a hard memory wall.",
    )
    source_types: list[EventType] | None = None
    limit: int = Field(default=5, ge=1, le=20)


class MemoryRetrievalScope(str, Enum):
    """Categorical scope chosen by a fresh stateless memory-routing call."""

    ACTIVE_ONLY = "ACTIVE_ONLY"
    HISTORY_ONLY = "HISTORY_ONLY"
    ACTIVE_AND_HISTORY = "ACTIVE_AND_HISTORY"


class MemoryNeedDecision(BaseModel):
    """Constrained model proposal for one MemoryNeed.

    The model never writes a search query or entity string. The application
    supplies a deterministic numbered anchor catalog derived from canonical
    input text; the model may only select existing catalog entries by index.
    """

    scope: MemoryRetrievalScope
    anchor_indices: list[int] = Field(default_factory=list, max_length=4)

    @model_validator(mode="after")
    def validate_anchor_selection(self) -> "MemoryNeedDecision":
        if any(index < 0 or index > 63 for index in self.anchor_indices):
            raise ValueError("anchor_indices must be between 0 and 63")
        if len(self.anchor_indices) != len(set(self.anchor_indices)):
            raise ValueError("anchor_indices must not contain duplicates")
        if self.scope is MemoryRetrievalScope.ACTIVE_ONLY and self.anchor_indices:
            raise ValueError("ACTIVE_ONLY must not select historical anchors")
        if self.scope is not MemoryRetrievalScope.ACTIVE_ONLY and not self.anchor_indices:
            raise ValueError("historical retrieval requires at least one anchor index")
        return self


class MemoryEvidence(BaseModel):
    """One canonical source event surfaced through the shared JIT Memory API."""

    source_event_id: UUID
    event_type: EventType
    source: str
    created_at: datetime
    conversation_id: UUID
    conversation_seq: int
    global_seq: int
    content: str
    score: float | None = None
    retrieval_reasons: list[str] = Field(default_factory=list)
    provenance_event_ids: list[UUID] = Field(default_factory=list)


class MemoryPacket(BaseModel):
    """Bounded internal evidence packet returned to any stateless agent."""

    memory_request_id: UUID
    origin: Literal[KnowledgeOrigin.INTERNAL_MEMORY] = KnowledgeOrigin.INTERNAL_MEMORY
    need: MemoryNeed
    supported: bool
    items: list[MemoryEvidence]
    retrieval_trace: dict[str, Any] = Field(default_factory=dict)


class RetrievalRequest(BaseModel):
    """Legacy MVP retrieval request retained for regression compatibility."""

    query_text: str | None = Field(
        default=None,
        description="Free-text description of the context needed, used for keyword search.",
    )
    conversation_scope: Literal["CURRENT_CONVERSATION", "ALL_CONVERSATIONS"] = "CURRENT_CONVERSATION"
    source_types: list[EventType] | None = Field(
        default=None, description="Restrict to these event types, if given."
    )
    ordering: Literal["CHRON_ASC", "CHRON_DESC", "RELEVANCE"] = "CHRON_DESC"
    limit: int = Field(default=5, ge=1, le=20)


class RetrievalItem(BaseModel):
    """One item returned by the legacy Retrieval Service."""

    source_event_id: UUID
    event_type: EventType
    created_at: datetime
    conversation_id: UUID
    conversation_seq: int
    global_seq: int
    content: str
    rank: float | None = None


class RetrievalResult(BaseModel):
    items: list[RetrievalItem]