"""Pydantic schemas for events and structured LLM communication.

Deterministic metadata (ids, timestamps, sequence numbers) is always
generated by application code, never by the LLM (spec section 8).
"""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, Field


class EventType(str, Enum):
    USER_PROMPT = "USER_PROMPT"
    AGENT_DECISION = "AGENT_DECISION"
    RETRIEVAL_REQUEST = "RETRIEVAL_REQUEST"
    RETRIEVAL_RESULT = "RETRIEVAL_RESULT"
    AGENT_RESPONSE = "AGENT_RESPONSE"
    SYSTEM_EVENT = "SYSTEM_EVENT"
    ERROR = "ERROR"


class Event(BaseModel):
    """A single row of the append-only event log, as read back from storage."""

    event_id: UUID
    conversation_id: UUID
    correlation_id: UUID
    global_seq: int
    conversation_seq: int
    event_type: EventType
    source: str
    created_at: datetime
    payload: dict[str, Any]
    schema_version: int = 1


class AgentAction(str, Enum):
    """The only two things the Primary Agent's classification step may decide."""

    RESPOND_DIRECTLY = "RESPOND_DIRECTLY"
    RETRIEVE_CONTEXT = "RETRIEVE_CONTEXT"


class RetrievalRequest(BaseModel):
    """Describes the information *need*, not the retrieval technique used.

    The Retrieval Service alone decides how to satisfy this (today: structured
    filters + Postgres full-text search; later: + vector similarity, etc.)
    """

    query_text: str | None = Field(
        default=None,
        description="Free-text description of the context needed, used for keyword search.",
    )
    conversation_scope: Literal["CURRENT_CONVERSATION", "ALL_CONVERSATIONS"] = "CURRENT_CONVERSATION"
    source_types: list[EventType] | None = Field(
        default=None, description="Restrict to these event types, if given."
    )
    ordering: Literal["CHRON_ASC", "CHRON_DESC", "RELEVANCE"] = "CHRON_DESC"
    limit: int = Field(default=5, ge=1, le=20)


class AgentDecision(BaseModel):
    """Structured, constrained output of the Primary Agent's classification step.

    Deliberately minimal: the LLM only decides *whether* context is needed and
    *what* it's looking for. Retrieval-policy parameters (scope, source types,
    ordering, limit) are application policy, constructed by ordinary Python in
    `primary_agent.build_retrieval_request`, not generated by the LLM.
    """

    action: AgentAction
    query_text: str | None = Field(
        default=None,
        description="Only set when action is RETRIEVE_CONTEXT: what to look for.",
    )


class RetrievalItem(BaseModel):
    """One piece of context returned by the Retrieval Service, verbatim.

    conversation_id/global_seq are only meaningful (and necessary) when a
    result set can span multiple conversations; conversation_seq is only
    meaningful within a single conversation. Carrying both lets the response
    step (or a human reading the persisted RETRIEVAL_RESULT event later)
    reconstruct exactly where evidence came from either way.
    """

    source_event_id: UUID
    event_type: EventType
    created_at: datetime
    conversation_id: UUID
    conversation_seq: int
    global_seq: int
    content: str
    rank: float | None = None


class RetrievalResult(BaseModel):
    items: list[RetrievalItem]
